name: Update Symbols Master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install xlsx

      - run: node scripts/updateSymbols.js

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "update symbols master" || echo "no change"
          git pull --rebase origin main
          git push origin main
